; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps = 
    SD
    adafruit/Adafruit FT6206 Library@^1.1.1
; 2. Inject C++20 and fix standard library macro conflicts
build_flags = 
    -std=gnu++17
monitor_speed = 115200  ; 👈 Add this line
; Force PlatformIO to ignore the STM32 SDRAM library for this environment
lib_ignore = Portenta_SDRAM
lib_ldf_mode = deep+
